version: "3.3"
services:
  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=root
      - MONGODB_INITDB_ROOT_PASSWORD=example
    command: --wiredTigerCacheSizeGB=0.50
    volumes: 
      - /data/mongo:/data/mongo

